<?xml version="1.0"?>
<package format="3">
  <name>aracne_description</name>
  <version>0.1.0</version>
  <description>URDF/Xacro description for the Aracne Mark I leg.</description>
  <maintainer email="user@example.com">Aracne Team</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>xacro</build_depend>
  <exec_depend>xacro</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
